version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  gateway:
    # image: frol555/gateway-service
    build: src/gateway-service/
    container_name: gateway-cont
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - event
      - info
      - pay
      - statistic


  auth:
    # image: frol555/bonus-service
    build: src/auth-service/
    container_name: auth-cont
    restart: on-failure
    ports:
      - "8010:8010"
    depends_on:
      - postgres

  event:
    # image: frol555/bonus-service
    build: src/event-service/
    container_name: event-cont
    restart: on-failure
    ports:
      - "8020:8020"
    depends_on:
      - postgres

  info:
    # image: frol555/bonus-service
    build: src/info-service/
    container_name: info-cont
    restart: on-failure
    ports:
      - "8030:8030"
    depends_on:
      - postgres

  pay:
    # image: frol555/bonus-service
    build: src/pay-service/
    container_name: pay-cont
    restart: on-failure
    ports:
      - "8040:8040"
    depends_on:
      - postgres

  statistic:
    # image: frol555/bonus-service
    build: src/statistic-service/
    container_name: statistic-cont
    restart: on-failure
    ports:
      - "8050:8050"
    depends_on:
      - postgres

volumes:
  db-data: