CREATE DATABASE users;
GRANT ALL PRIVILEGES ON DATABASE tickets TO program;

CREATE DATABASE events;
GRANT ALL PRIVILEGES ON DATABASE flights TO program;

CREATE DATABASE history;
GRANT ALL PRIVILEGES ON DATABASE privileges TO program;
